CREATE TABLE tourist_info (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `location_id` INT NOT NULL,
    `language` VARCHAR(50) NOT NULL,
    `currency` VARCHAR(50) NOT NULL,
    `NationalID` VARCHAR(50) NOT NULL UNIQUE,
    `name` VARCHAR(255),
    `ranking` VARCHAR(255),
    `description` TEXT,
    `rating` DECIMAL(3,1),
    `num_reviews` INT,
    `website` VARCHAR(255),
    `address` VARCHAR(255),
    `phone` VARCHAR(25),
    `write_review` VARCHAR(255),
    `monday_open` INT,
    `monday_close` INT,
    `tuesday_open` INT,
    `tuesday_close` INT,
    `wednesday_open` INT,
    `wednesday_close` INT,
    `thursday_open` INT,
    `thursday_close` INT,
    `friday_open` INT,
    `friday_close` INT,
    `saturday_open` INT,
    `saturday_close` INT,
    `sunday_open` INT,
    `sunday_close` INT,
    `popular_tour_title` VARCHAR(255),
    `primary_category` VARCHAR(50),
    `price` VARCHAR(10),
    `partner` VARCHAR(50),
    `tour_url` VARCHAR(500),
    `product_code` VARCHAR(50),
    `is_api` tinyint(1) NOT NULL DEFAULT 0
);